version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8888:8888"
    volumes:
      - ./backend:/app
      - ./data:/app/data  # 将 SQLite 数据文件挂载到后端容器中
    

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
